/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_manuelvalladares_11711089;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author mevl1
 */
public class PRINCIPAL extends javax.swing.JFrame {
    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        Hilo h=new Hilo(jl_hora);
        Thread proceso1=new Thread(h);
        proceso1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ATM = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Crear_Usuarios = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jd_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jd_afiliacion = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        tf_nombre2 = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_apellido2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        Cuenta = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        tf_numCuenta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_saldoInicial = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_idPropio = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        SEL_CUENTA = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        cb_sel_cuenta = new javax.swing.JComboBox<>();
        RETIROS = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        tf_cantidad = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        DEPOSITO = new javax.swing.JDialog();
        jButton8 = new javax.swing.JButton();
        PERSONAL = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        tf_dep_personal = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        DEP_OTRO = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        cb_dep = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jl_hora = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Retiros");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel9.setText("Revisar Transacciones");

        jLabel6.setText("Deposito");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setText("Estado de Cuenta");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel7.setText("Crear Cuenta");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jButton6.setText("Selecciona");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel4.setText("Cuenta");

        jLabel26.setText("Imprimir recibo");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(168, 311, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(25, 25, 25))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel26)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButton6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addGap(33, 33, 33)
                .addComponent(jLabel26)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ATMLayout = new javax.swing.GroupLayout(ATM.getContentPane());
        ATM.getContentPane().setLayout(ATMLayout);
        ATMLayout.setHorizontalGroup(
            ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ATMLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ATMLayout.setVerticalGroup(
            ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ATMLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setText("Nombre");

        jLabel11.setText("2 Nombre");

        jLabel12.setText("Apellido");

        jLabel13.setText("2 Apellido");

        jLabel14.setText("Nacimiento");

        jLabel15.setText("Afiliacion");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel16.setText("Contraseña");

        jLabel17.setText("Usuario");

        javax.swing.GroupLayout Crear_UsuariosLayout = new javax.swing.GroupLayout(Crear_Usuarios.getContentPane());
        Crear_Usuarios.getContentPane().setLayout(Crear_UsuariosLayout);
        Crear_UsuariosLayout.setHorizontalGroup(
            Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_UsuariosLayout.createSequentialGroup()
                        .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(69, 69, 69))
                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                        .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jd_afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jd_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_UsuariosLayout.createSequentialGroup()
                        .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16)
                                        .addGap(30, 30, 30))
                                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                                            .addComponent(tf_usuario)))))
                            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        Crear_UsuariosLayout.setVerticalGroup(
            Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_UsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton4))
                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addGap(13, 13, 13)
                .addComponent(tf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jd_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jd_afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel18.setText("numero de cuenta");

        jLabel19.setText("Saldo Inicial");

        jLabel20.setText("ID Propio");

        jButton5.setText("Crear Cuenta");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CuentaLayout = new javax.swing.GroupLayout(Cuenta.getContentPane());
        Cuenta.getContentPane().setLayout(CuentaLayout);
        CuentaLayout.setHorizontalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_numCuenta)
                        .addGroup(CuentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tf_saldoInicial)
                        .addGroup(CuentaLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel20))
                        .addComponent(tf_idPropio)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        CuentaLayout.setVerticalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuentaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addGap(28, 28, 28)
                .addComponent(tf_saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addGap(29, 29, 29)
                .addComponent(tf_idPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel21.setText("Seleccione Cuenta");

        javax.swing.GroupLayout SEL_CUENTALayout = new javax.swing.GroupLayout(SEL_CUENTA.getContentPane());
        SEL_CUENTA.getContentPane().setLayout(SEL_CUENTALayout);
        SEL_CUENTALayout.setHorizontalGroup(
            SEL_CUENTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SEL_CUENTALayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(SEL_CUENTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(cb_sel_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        SEL_CUENTALayout.setVerticalGroup(
            SEL_CUENTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SEL_CUENTALayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addGap(33, 33, 33)
                .addComponent(cb_sel_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel22.setText("Ingrese la cantidad");

        jButton7.setText("Retirar");

        javax.swing.GroupLayout RETIROSLayout = new javax.swing.GroupLayout(RETIROS.getContentPane());
        RETIROS.getContentPane().setLayout(RETIROSLayout);
        RETIROSLayout.setHorizontalGroup(
            RETIROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RETIROSLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(RETIROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        RETIROSLayout.setVerticalGroup(
            RETIROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RETIROSLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton7)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jButton8.setText("Personal");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DEPOSITOLayout = new javax.swing.GroupLayout(DEPOSITO.getContentPane());
        DEPOSITO.getContentPane().setLayout(DEPOSITOLayout);
        DEPOSITOLayout.setHorizontalGroup(
            DEPOSITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSITOLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton8)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        DEPOSITOLayout.setVerticalGroup(
            DEPOSITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSITOLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton8)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel23.setText("Ingrese la cantidad");

        jButton10.setText("Depositar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PERSONALLayout = new javax.swing.GroupLayout(PERSONAL.getContentPane());
        PERSONAL.getContentPane().setLayout(PERSONALLayout);
        PERSONALLayout.setHorizontalGroup(
            PERSONALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PERSONALLayout.createSequentialGroup()
                .addGroup(PERSONALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PERSONALLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel23))
                    .addGroup(PERSONALLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(PERSONALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(tf_dep_personal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        PERSONALLayout.setVerticalGroup(
            PERSONALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PERSONALLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel23)
                .addGap(39, 39, 39)
                .addComponent(tf_dep_personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton10)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jLabel24.setText("Seleccione cuenta");

        jLabel25.setText("Ingrese el deposito");

        jButton11.setText("Depositar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DEP_OTROLayout = new javax.swing.GroupLayout(DEP_OTRO.getContentPane());
        DEP_OTRO.getContentPane().setLayout(DEP_OTROLayout);
        DEP_OTROLayout.setHorizontalGroup(
            DEP_OTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEP_OTROLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(DEP_OTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addGroup(DEP_OTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DEP_OTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_dep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jTextField1)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        DEP_OTROLayout.setVerticalGroup(
            DEP_OTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEP_OTROLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(cb_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel25)
                .addGap(37, 37, 37)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton11)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear Usuario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear ATM");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("ATM");

        jLabel2.setText("ID Usuario");

        jLabel3.setText("Contraseña");

        jButton3.setText("Iniciar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jl_hora.setText("0:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jl_hora)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_user)
                            .addComponent(tf_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton3)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jl_hora)))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(172, 172, 172)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Crear_Usuarios.setModal(true);
        Crear_Usuarios.pack();
        Crear_Usuarios.setLocationRelativeTo(this);
        Crear_Usuarios.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ap = new Admin_Usuario("./users.cbm");
        ap.cargarArchivo();
        //String user, String nombre, String nombre2, String apellido, String apellido2, String contraseña, Date nacimiento, Date afiliacion, double transacciones
        String nombre, apellido, nombre2, apellido2, contraseña, user;
        Date fecha, afiliacion;
        nombre = tf_nombre.getText();
        apellido = tf_apellido.getText();
        nombre2 = tf_nombre2.getText();
        apellido2 = tf_apellido2.getText();
        fecha = jd_nacimiento.getDate();
        afiliacion = jd_afiliacion.getDate();
        contraseña = tf_contraseña.getText();
        user = tf_usuario.getText();
        USUARIOS m = new USUARIOS(user, nombre, nombre2, apellido, apellido2, contraseña, fecha, afiliacion, 0);
        ap.getUsuarios().add(m);

        ap.escribirArchivo();

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        trans="";
        String user, contra;
        user = tf_user.getText();
        boolean ver = false;
        contra = tf_pass.getText();
        for (USUARIOS i : ad_u.getUsuarios()) {
            System.out.println(i.getUser() + " " + i.getContraseña());
            if (i.getUser().equals(user) && i.getContraseña().equals(contra)) {
                index = ad_u.getUsuarios().indexOf(i);
                ver = true;
            }
        }
        if (ver == true) {
            ATM.setModal(true);
            ATM.pack();
            ATM.setLocationRelativeTo(this);
            ATM.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Cuenta.setModal(true);
        Cuenta.pack();
        Cuenta.setLocationRelativeTo(this);
        Cuenta.setVisible(true);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        Admin_Cuentas ac=new Admin_Cuentas("./cuentas.mev");
        ad_u.cargarArchivo();
        String num, id;
        Double saldo;
        num = tf_numCuenta.getText();
        id = tf_idPropio.getText();
        saldo = Double.parseDouble(tf_saldoInicial.getText());
        Cuenta c = new Cuenta(num, saldo, id);
        ad_u.getUsuarios().get(index).getCuentas().add(c);
        ad_u.escribirArchivo();
        cuentas.add(c);
        ac.escribirArchivo();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_sel_cuenta.getModel();
        m.removeAllElements();
        for (Object i : ad_u.getUsuarios().get(index).getCuentas()) {
            m.addElement(i);
        }
        SEL_CUENTA.setModal(true);
        SEL_CUENTA.pack();
        SEL_CUENTA.setLocationRelativeTo(this);
        SEL_CUENTA.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        RETIROS.setModal(true);
        RETIROS.pack();
        RETIROS.setLocationRelativeTo(this);
        RETIROS.setVisible(true);
        int c = cb_sel_cuenta.getSelectedIndex();
        double saldo = ad_u.getUsuarios().get(index).getCuentas().get(c).getSaldo();
        double retiro = Double.parseDouble(tf_cantidad.getText());
        trans+="Retiro "+retiro+"\n";
        if (saldo < retiro) {
            JOptionPane.showMessageDialog(this, "No cuenta con el saldo suficiente");
        } else {
            JOptionPane.showMessageDialog(this, "Retiro exitoso");
        }
        double nuevo = saldo - retiro;
        ad_u.getUsuarios().get(index).getCuentas().get(c).setSaldo(nuevo);
        ad_u.escribirArchivo();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        DEPOSITO.setModal(true);
        DEPOSITO.pack();
        DEPOSITO.setLocationRelativeTo(this);
        DEPOSITO.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        PERSONAL.setModal(true);
        PERSONAL.pack();
        PERSONAL.setLocationRelativeTo(this);
        PERSONAL.setVisible(true);

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        int cuenta = cb_sel_cuenta.getSelectedIndex();
        double dep = Double.parseDouble(tf_dep_personal.getText());
        double saldo = ad_u.getUsuarios().get(index).getCuentas().get(cuenta).getSaldo();
        double nuevo = saldo + dep;
        trans+="Deposito "+nuevo+"\n";
        ad_u.getUsuarios().get(index).getCuentas().get(cuenta).setSaldo(nuevo);
        JOptionPane.showMessageDialog(this, "Deposito Exitoso");
        ad_u.escribirArchivo();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        String a =cb_dep.getSelectedItem().toString();
        int s=0;
        for (USUARIOS i : ad_u.getUsuarios()) {
            if (i.getCuentas().toString().contains(a)) {
                System.out.println(a);
            }
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        double a=ad_u.getUsuarios().get(index).getCuentas().get(cb_sel_cuenta.getSelectedIndex()).getSaldo();
        JOptionPane.showMessageDialog(this,"Su saldo es : \n"+a);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
           Admin_Usuario ad_u = new Admin_Usuario("./users.cbm");
        ad_u.cargarArchivo();
        double a=ad_u.getUsuarios().get(index).getCuentas().get(cb_sel_cuenta.getSelectedIndex()).getSaldo();
        System.out.println(trans);
        System.out.println("saldo en cuenta "+a);
    }//GEN-LAST:event_jLabel26MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ATM;
    private javax.swing.JDialog Crear_Usuarios;
    private javax.swing.JDialog Cuenta;
    private javax.swing.JDialog DEPOSITO;
    private javax.swing.JDialog DEP_OTRO;
    private javax.swing.JDialog PERSONAL;
    private javax.swing.JDialog RETIROS;
    private javax.swing.JDialog SEL_CUENTA;
    private javax.swing.JComboBox<String> cb_dep;
    private javax.swing.JComboBox<String> cb_sel_cuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser jd_afiliacion;
    private com.toedter.calendar.JDateChooser jd_nacimiento;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_apellido2;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_dep_personal;
    private javax.swing.JTextField tf_idPropio;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_numCuenta;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_saldoInicial;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
int index;
    ArrayList cuentas = new ArrayList();
    String trans;
}
